version: 2

models:
  - name: stg_channels
    description: Normalisation des canaux marketing.
    columns:
      - name: channel_id
        tests: [not_null, unique]
      - name: channel_name
        tests: [not_null]
      - name: channel_group
        tests:
          - not_null
          - accepted_values:
              arguments:
                values: ['Paid Search', 'Paid Social', 'Owned', 'Organic']

  - name: stg_campaigns
    description: Normalisation des campagnes marketing.
    columns:
      - name: campaign_id
        tests: [not_null, unique]
      - name: campaign_name
        tests: [not_null]
      - name: objective
        tests:
          - not_null
          - accepted_values:
              arguments:
                values: ['Acquisition', 'Conversion', 'Retention']
      - name: start_date
        tests: [not_null]
      - name: end_date
        tests: [not_null]

  - name: stg_campaign_channel_daily
    description: Base journalière de performance campagne x canal.
    columns:
      - name: date_day
        tests: [not_null]
      - name: campaign_id
        tests:
          - not_null
          - relationships:
              arguments:
                to: ref('stg_campaigns')
                field: campaign_id
      - name: channel_id
        tests:
          - not_null
          - relationships:
              arguments:
                to: ref('stg_channels')
                field: channel_id
      - name: impressions
        tests: [not_null]
      - name: clicks
        tests: [not_null]
      - name: conversions
        tests: [not_null]
      - name: spend
        tests: [not_null]
      - name: revenue
        tests: [not_null]
